# App settings
quarkus.application.name=db-migration
quarkus.http.port=8080

# Database configurations
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:DRAGON}
quarkus.datasource.password=${DB_PASS:DRAGON}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:PAYMENT_GATEWAY}

# Flyway settings
quarkus.flyway.migrate-at-start=true

quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common

