# Product Service configuration
quarkus.log.level=INFO

quarkus.grpc.clients.merchant.host=${MERCHANT_HOST:localhost}
quarkus.grpc.clients.merchant.port=${MERCHANT_GRPC_PORT:9005}

quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common
