quarkus.grpc.server.port=9005
quarkus.grpc.server.host=0.0.0.0

quarkus.http.port=8085
quarkus.http.host=0.0.0.0

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:merchant_svc}
quarkus.datasource.password=${DB_PASS:merchant_svc_pass}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5430}/${DB_NAME:merchant_db}

quarkus.arc.remove-unused-beans=true
quarkus.grpc.server.use-separate-server=true

quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false

quarkus.log.level=INFO
quarkus.log.category."com.sanedge".level=DEBUG

quarkus.grpc.clients.user.host=${USER_SERVICE_HOST:localhost}
quarkus.grpc.clients.user.port=${USER_SERVICE_GRPC_PORT:9011}
