# Order Service configuration
quarkus.log.level=INFO

quarkus.grpc.server.port=9001
quarkus.grpc.server.host=0.0.0.0
quarkus.grpc.server.use-separate-server=true

quarkus.grpc.clients.cashier.host=${CASHIER_HOST:localhost}
quarkus.grpc.clients.cashier.port=${CASHIER_GRPC_PORT:9014}
quarkus.grpc.clients.merchant.host=${MERCHANT_HOST:localhost}
quarkus.grpc.clients.merchant.port=${MERCHANT_GRPC_PORT:9005}
quarkus.grpc.clients.order_item.host=${ORDER_ITEM_HOST:localhost}
quarkus.grpc.clients.order_item.port=${ORDER_ITEM_GRPC_PORT:9016}
quarkus.grpc.clients.product.host=${PRODUCT_HOST:localhost}
quarkus.grpc.clients.product.port=${PRODUCT_GRPC_PORT:9003}

quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:DRAGON}
quarkus.datasource.password=${DB_PASS:DRAGON}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:PAYMENT_GATEWAY}
