quarkus.application.name=gateway
quarkus.http.port=8080

quarkus.grpc.clients.userservice.host=${USER_SERVICE_HOST:localhost}
quarkus.grpc.clients.userservice.port=${USER_SERVICE_GRPC_PORT:8081}


quarkus.grpc.clients.productservice.host=${PRODUCT_SERVICE_HOST:localhost}
quarkus.grpc.clients.productservice.port=${PRODUCT_SERVICE_GRPC_PORT:8082}

quarkus.grpc.clients.orderservice.host=${ORDER_SERVICE_HOST:localhost}
quarkus.grpc.clients.orderservice.port=${ORDER_SERVICE_GRPC_PORT:8083}

quarkus.grpc.clients.auth.host=${AUTH_HOST:localhost}
quarkus.grpc.clients.auth.port=${AUTH_GRPC_PORT:9012}

quarkus.grpc.clients.user.host=${USER_HOST:localhost}
quarkus.grpc.clients.user.port=${USER_GRPC_PORT:9011}

quarkus.grpc.clients.card.host=${CARD_HOST:localhost}
quarkus.grpc.clients.card.port=${CARD_GRPC_PORT:9004}

quarkus.grpc.clients.merchant.host=${MERCHANT_HOST:localhost}
quarkus.grpc.clients.merchant.port=${MERCHANT_GRPC_PORT:9005}

quarkus.grpc.clients.role.host=${ROLE_HOST:localhost}
quarkus.grpc.clients.role.port=${ROLE_GRPC_PORT:9006}

quarkus.grpc.clients.saldo.host=${SALDO_HOST:localhost}
quarkus.grpc.clients.saldo.port=${SALDO_GRPC_PORT:9007}

quarkus.grpc.clients.topup.host=${TOPUP_HOST:localhost}
quarkus.grpc.clients.topup.port=${TOPUP_GRPC_PORT:9008}

quarkus.grpc.clients.transaction.host=${TRANSACTION_HOST:localhost}
quarkus.grpc.clients.transaction.port=${TRANSACTION_GRPC_PORT:9009}

quarkus.grpc.clients.transfer.host=${TRANSFER_HOST:localhost}
quarkus.grpc.clients.transfer.port=${TRANSFER_GRPC_PORT:9010}

quarkus.grpc.clients.withdraw.host=${WITHDRAW_HOST:localhost}
quarkus.grpc.clients.withdraw.port=${WITHDRAW_GRPC_PORT:9012}

quarkus.grpc.clients.cashier.host=${CASHIER_HOST:localhost}
quarkus.grpc.clients.cashier.port=${CASHIER_GRPC_PORT:9014}

quarkus.grpc.clients.category.host=${CATEGORY_HOST:localhost}
quarkus.grpc.clients.category.port=${CATEGORY_GRPC_PORT:9015}

quarkus.grpc.clients.order_item.host=${ORDER_ITEM_HOST:localhost}
quarkus.grpc.clients.order_item.port=${ORDER_ITEM_GRPC_PORT:9016}

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Modular Monolith API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Gateway REST API backed by internal gRPC services


quarkus.log.level=INFO
quarkus.log.category."com.sanedge".level=DEBUG
