quarkus.grpc.server.port=9006
quarkus.grpc.server.host=0.0.0.0

quarkus.http.port=8086
quarkus.http.host=0.0.0.0

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:DRAGON}
quarkus.datasource.password=${DB_PASS:DRAGON}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:PAYMENT_GATEWAY}

quarkus.arc.remove-unused-beans=true
quarkus.grpc.server.use-separate-server=true

quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=false

quarkus.log.level=INFO
quarkus.log.category."com.sanedge".level=DEBUG


quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common
