quarkus.grpc.server.port=9016
quarkus.grpc.server.host=0.0.0.0
quarkus.grpc.server.use-separate-server=true

quarkus.grpc.clients.order.host=${ORDER_HOST:localhost}
quarkus.grpc.clients.order.port=${ORDER_GRPC_PORT:9001}
quarkus.grpc.clients.product.host=${PRODUCT_HOST:localhost}
quarkus.grpc.clients.product.port=${PRODUCT_GRPC_PORT:9003}

quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common


quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common


quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:DRAGON}
quarkus.datasource.password=${DB_PASS:DRAGON}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:PAYMENT_GATEWAY}
