apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pointofsale

resources:
- common/
- postgres/
- redis/
- kafka/
- db-migration/
- apigateway/
- auth/
- role/
- user/
- merchant/
- transaction/
- cashier/
- category/
- product/
- order/
- order_item/
- email/
- nginx/
- observability/
