quarkus.grpc.server.port=9014
quarkus.grpc.server.host=0.0.0.0
quarkus.grpc.server.use-separate-server=true

quarkus.grpc.clients.merchant.host=${MERCHANT_HOST:localhost}
quarkus.grpc.clients.merchant.port=${MERCHANT_GRPC_PORT:9005}
quarkus.grpc.clients.user.host=${USER_GRPC_HOST:localhost}
quarkus.grpc.clients.user.port=${USER_GRPC_PORT:9011}

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:DRAGON}
quarkus.datasource.password=${DB_PASS:DRAGON}
quarkus.datasource.reactive.url=postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:PAYMENT_GATEWAY}



quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common
