# Transaction Service configuration
quarkus.log.level=INFO

quarkus.grpc.clients.merchant.host=${MERCHANT_HOST:localhost}
quarkus.grpc.clients.merchant.port=${MERCHANT_GRPC_PORT:50054}

quarkus.grpc.clients.order.host=${ORDER_HOST:localhost}
quarkus.grpc.clients.order.port=${ORDER_GRPC_PORT:8084}

quarkus.grpc.clients.order_item.host=${ORDER_ITEM_HOST:localhost}
quarkus.grpc.clients.order_item.port=${ORDER_ITEM_GRPC_PORT:8085}

quarkus.index-dependency.common.group-id=com.sanedge
quarkus.index-dependency.common.artifact-id=common

