quarkus.http.port=8092
quarkus.http.host=0.0.0.0

quarkus.arc.remove-unused-beans=true

# Mailer configuration
quarkus.mailer.host=${SMTP_SERVER:localhost}
quarkus.mailer.port=${SMTP_PORT:587}
quarkus.mailer.username=${SMTP_USER:}
quarkus.mailer.password=${SMTP_PASS:}
quarkus.mailer.ssl=false
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.from=no-reply@payment-gateway.com

quarkus.log.level=INFO
quarkus.log.category."com.sanedge".level=DEBUG
