apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: point-of-sale-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: pos
  source:
    repoURL: https://github.com/MamangRust/modular-monolith-quarkus-point-of-sale.git
    targetRevision: main
    path: deployments/gitops/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
